# Generated by Django 4.1.2 on 2022-10-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
                ('description', models.CharField(max_length=4096, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
                ('value', models.CharField(max_length=2048, verbose_name='Value')),
                ('description', models.CharField(max_length=4096, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.CharField(max_length=2048, verbose_name='Directory Path')),
                ('file_name', models.CharField(max_length=2048, verbose_name='File Name')),
                ('file_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.CharField(max_length=2048, verbose_name='Directory Path')),
                ('file_name', models.CharField(max_length=2048, verbose_name='File Name')),
                ('file_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=2048, verbose_name='Points')),
                ('description', models.CharField(max_length=4096, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.annotation')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.color')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.image')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.polygon')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
                ('description', models.CharField(max_length=4096, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4096, verbose_name='Value')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.segment')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4096, verbose_name='Value')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.image')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.image')),
                ('mask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontal.mask')),
            ],
        ),
    ]
