# Generated by Django 4.1.2 on 2022-11-12 13:42

from django.db import migrations, models
import frontal.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='directory_path',
            field=models.FilePathField(path=frontal.models.images_path),
        ),
    ]
