# Generated by Django 4.1.2 on 2022-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontal', '0002_alter_image_directory_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='directory_path',
            field=models.FilePathField(),
        ),
    ]
